homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 45.178800
  longitude: -93.732480
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 299
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  temperature_unit: F
  customize: !include customize.yaml
  auth_providers:
   - type: trusted_networks

zone:
  name: Home
  latitude: 45.178800
  longitude: -93.732480
  icon: mdi:home
  radius: 500

# Enables configuration UI
config:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-iframe.html

ios:

emulated_hue:
  # listen_port: 8300
  expose_by_default: false
  host_ip: 192.168.0.150

wemo:
  static:
    - 192.168.0.180
    - 192.168.0.181
    - 192.168.0.182

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_pass
  trusted_networks:
    - 127.0.0.1
    - 192.168.0.0/24

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  db_url: 'mysql://hass:killians1@192.168.0.165/hass_db'
  purge_keep_days: 720

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: error
  logs:
    homeassistant.components.cameras: fatal

# Track the sun
sun:

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0xA8,0x30,0xAF,0xC9,0x41,0x3F,0x8F,0xE2,0x37,0x37,0xAB,0xCC,0x5E,0x3A,0x59,0x79"
  polling_interval: 30000
  device_config:
    light.level:
      polling_intensity: 1
#	All these polling lines should help get status of front porch light

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.0.163:81/videostream.cgi?user=admin&pwd=minicooper
    name: Front Door
    #username: admin
    #password: !secret camera_password 

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

notify:
  - name: twilio
    platform: twilio_sms
    from_number: +19133254454
  - name:  parent_iphones
    platform: group
    services:
      - service: ios_amb_iphone
      - service: ios_rob
      - service: ios_aidan
      - service: ios_nadias_iphone 

mqtt:
  broker: ha.widgetninja.net
  port: 1883
  client_id: home-assistant-1
  username: mosquitto 
  password: !secret mosquitto_password

switch:
  - platform: mqtt
    name: "Doorbell"
    state_topic: "/esp/doorbell/state"
    command_topic: "/esp/doorbell/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimisitic: False
  - platform: mqtt
    name: "Garage Door One"
    state_topic: "/esp/garageDoorOne/state"
    command_topic: "/esp/garageDoorOne/set"
    payload_on: "1"
    payload_off: "0"
    optimisitic: False
  - platform: mqtt
    name: "Garage Door Two"
    state_topic: "/esp/garageDoorTwo/state"
    command_topic: "/esp/garageDoorTwo/set"
    payload_on: "1"
    payload_off: "0"
    optimisitic: False

sensor:
  - platform: darksky
    api_key: !secret darksky_api
    monitored_conditions:
      - summary
      - daily_summary
      - icon
      - temperature
      - humidity
      - precip_probability
      - precip_intensity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon

  - platform: template
    sensors:
      iframe:
        value_template: iframe
  - platform: mqtt
    name: "LakeTemp"
    state_topic: "/esp/beBeeLakeTemp"
    qos: 0
    unit_of_measurement: "F"

binary_sensor:
  - platform: mqtt
    state_topic: "/esp/garageDoorOne/state"
    name: "Garage Door One"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    device_class: opening
  - platform: mqtt
    state_topic: "/esp/garageDoorTwo/state"
    name: "Garage Door Two"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    device_class: opening

light:
  - platform: mqtt
    name: 'Family Room Status Light'
    state_topic: '/upstairsFamilyRoom/statusLight/light/status'
    command_topic: '/upstairsFamilyRoom/statusLight/light/set'
    brightness_state_topic: '/upstairsFamilyRoom/statusLight/brightness/status'
    brightness_command_topic: '/upstairsFamilyRoom/statusLight/brightness/set'
    rgb_state_topic: '/upstairsFamilyRoom/statusLight/rgb/status'
    rgb_command_topic: '/upstairsFamilyRoom/statusLight/rgb/set'
    brightness_scale: 100
    optimistic: false

group: !include groups.yaml

automation: !include automations.yaml

automation old:
  - id: textOnDoorbellPress
    alias: Text on doorbell press
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: mqtt
        topic: "/esp/doorbell/state"
        payload: 'ON'
    action:
      service: notify.parent_iphones
      data:
        title: "Doorbell"
        message: "Don't tell the land shark."
        data:
          push:
            thread-id: "doorbell"
            category: camera
          entity_id: camera.front_door
